# Stage 2 synthesis CV (Section 5.3)

Act IV synthesis CV (`StratifiedGroupKFold` on `experimental_group`, 10-fold default).

**Stage 1:** fit **once** per training scenario (A/B/C) on the official train/test split (§5.2); pooled test metrics in logs mix cohorts — use the **Stage 1 classification table** cell for Brad vs Liberman columns. **Stage 2** only is refit per CV fold.

**Artifacts (separate by fold count):**
- **10-fold:** `figures/cache/stage2_synthesis_cv_{folds,progress,summary}.*` (legacy names)
- **5-fold:** `figures/cache/stage2_synthesis_cv_5fold_*`

Set `FORCE_RERUN` per run below. Completed keys are skipped within each fold-count cache.

In [1]:
import importlib
import json
from pathlib import Path

import pandas as pd

import utils.stage2_synthesis_cv as _synthesis_cv
import utils.stage2_synthesis_plot as _synthesis_plot

importlib.reload(_synthesis_cv)
importlib.reload(_synthesis_plot)

from utils.benchmark_metrics import (
    LIBERMAN_GROUP_MEAN_BASELINE_PARQUET,
    STAGE2_BEST_HP_DIR,
    STAGE2_SYNTHESIS_CV_OOF_PARQUET,
    STAGE2_SYNTHESIS_CV_OOF_R2_SUMMARY_PARQUET,
    STAGE2_SYNTHESIS_CV_POOLED_OOF_PARQUET,
    STAGE2_SYNTHESIS_STAGE1_TABLE_PARQUET,
    stage2_synthesis_cv_paths,
)
from utils.nn_stage2_data import load_nn_stage2_data
from utils.stage2_hp import resolve_torch_device
from utils.stage2_synthesis_cv import (
    build_stage1_classification_table,
    compute_pooled_synthesis_folds,
    panel_c_rmse_report_table,
    pooled_oof_r2_report_table,
    run_synthesis_cv,
    summarize_pooled_folds,
    summarize_pooled_oof_r2,
)
from utils.stage2_synthesis_plot import (
    synthesis_act4_grid_cv,
    synthesis_cohort_panels_3cv,
    synthesis_cohort_panels_3cv_r2,
    synthesis_cohort_panels_cv,
)
from utils.subject_cv import eval_stratum_mean_baseline_cv

device = resolve_torch_device()
print("device:", device)

device: mps

In [2]:
# Stage 1 classification: per-cohort + pooled overall test acc/AUC (33 animals)
stage1_table = build_stage1_classification_table(verbose=True)
stage1_table.to_parquet(STAGE2_SYNTHESIS_STAGE1_TABLE_PARQUET, index=False)
display(
    stage1_table[
        [
            "scenario",
            "training_data",
            "brad_test_acc",
            "brad_test_auc",
            "liberman_test_acc",
            "liberman_test_auc",
            "overall_test_acc",
            "overall_test_auc",
        ]
    ].round(3)
)

=== Stage 1 table: within-cohort (Brad) ===
           Selected RF  — fit acc (animal@cal): 0.944 | non-test acc (animal@cal): 0.933 | threshold (Fit+Val): 0.423 | test acc (animal@cal): 0.917 | test acc@0.5: 0.583 | AUC: 0.944

=== Stage 1 table: within-cohort (Liberman) ===
           Selected RF  — fit acc (animal@cal): 0.971 | non-test acc (animal@cal): 0.940 | threshold (Fit+Val): 0.556 | test acc (animal@cal): 0.952 | test acc@0.5: 0.810 | AUC: 0.909

=== Stage 1 table: cross-cohort (train Brad → test Liberman) ===
           Selected RF  — fit acc (animal@cal): 0.944 | non-test acc (animal@cal): 0.933 | threshold (Fit+Val): 0.423 | test acc (animal@cal): 0.619 | test acc@0.5: 0.905 | AUC: 0.936

=== Stage 1 table: cross-cohort (train Liberman → test Brad) ===
           Selected RF  — fit acc (animal@cal): 0.971 | non-test acc (animal@cal): 0.940 | threshold (Fit+Val): 0.556 | test acc (animal@cal): 0.500 | test acc@0.5: 0.500 | AUC: 0.194

=== Stage 1 table: combined training ===
           Selected RF  — fit acc (animal@cal): 0.865 | non-test acc (animal@cal): 0.860 | threshold (Fit+Val): 0.458 | test acc (animal@cal): 0.788 | test acc@0.5: 0.727 | AUC: 0.805

,scenario,training_data,brad_test_acc,brad_test_auc,liberman_test_acc,liberman_test_auc
0,1,Within-cohort,0.917,0.944,0.952,0.909
1,2,Cross-cohort,0.500,0.194,0.619,0.936
2,3,Combined,0.833,0.722,0.762,0.918

In [3]:
hp = {}
for scen in ("A", "B", "C"):
    p = STAGE2_BEST_HP_DIR / f"{scen}.json"
    hp[scen] = json.loads(p.read_text())

# (n_splits, force_rerun) — separate cache files per fold count
# After feature changes (e.g. strain_binary), delete stage2_synthesis_cv_* parquets
# or set force_rerun=True for that run entry.
SYNTHESIS_RUNS = [
    (10, True),  # legacy paths; skip if already complete
    (5, True),  # figures/cache/stage2_synthesis_cv_5fold_*
]
summaries = {}
for n_folds, force_rerun in SYNTHESIS_RUNS:
    _, summary = run_synthesis_cv(
        hp,
        device=device,
        n_splits=n_folds,
        force_rerun=force_rerun,
        verbose=True,
    )
    summaries[n_folds] = summary
    print(stage2_synthesis_cv_paths(n_folds)[2])

summary_10 = summaries[10]
summary_5 = summaries[5]
summary_10

Synthesis CV: 10-fold → stage2_synthesis_cv_summary.parquet

=== Global Stage 1 (per training scenario A/B/C) ===
           Selected RF  — fit acc (animal@cal): 0.944 | non-test acc (animal@cal): 0.933 | threshold (Fit+Val): 0.423 | test acc (animal@cal): 0.917 | test acc@0.5: 0.583 | AUC: 0.944
  global S1 scen=A (RF): fit/val 45 animals, official test 12 animals, labels for 162 animals | Brad test acc=0.917 AUC=0.944 | Lib test acc=nan AUC=nan
           Selected RF  — fit acc (animal@cal): 0.865 | non-test acc (animal@cal): 0.860 | threshold (Fit+Val): 0.458 | test acc (animal@cal): 0.788 | test acc@0.5: 0.727 | AUC: 0.805
  global S1 scen=B (RF): fit/val 129 animals, official test 33 animals, labels for 162 animals | Brad test acc=0.833 AUC=0.722 | Lib test acc=0.762 AUC=0.918
           Selected RF  — fit acc (animal@cal): 0.971 | non-test acc (animal@cal): 0.940 | threshold (Fit+Val): 0.556 | test acc (animal@cal): 0.952 | test acc@0.5: 0.810 | AUC: 0.909
  global S1 scen=C (RF): fit/val 84 animals, official test 21 animals, labels for 162 animals | Brad test acc=nan AUC=nan | Lib test acc=0.952 AUC=0.909
Brad fold 0 ceiling rmse=2.3565
Brad f0 scen=A L7 rmse=3.2349
Brad f0 scen=A RF rmse=2.2503
Brad f0 scen=A XGB rmse=2.0290
Brad f0 scen=A MLP rmse=1.5745
Brad f0 scen=B L7 rmse=3.0005
Brad f0 scen=B RF rmse=2.4302
Brad f0 scen=B XGB rmse=2.1100
Brad f0 scen=B MLP rmse=1.7526
Brad f0 scen=C L7 rmse=3.3597
Brad f0 scen=C RF rmse=4.0246
Brad f0 scen=C XGB rmse=4.2417
Brad f0 scen=C MLP rmse=3.4220
Brad fold 1 ceiling rmse=2.7300
Brad f1 scen=A L7 rmse=3.3184
Brad f1 scen=A RF rmse=2.7741
Brad f1 scen=A XGB rmse=2.5116
Brad f1 scen=A MLP rmse=2.4585
Brad f1 scen=B L7 rmse=3.6421
Brad f1 scen=B RF rmse=3.1132
Brad f1 scen=B XGB rmse=2.9561
Brad f1 scen=B MLP rmse=2.2343
Brad f1 scen=C L7 rmse=4.0795
Brad f1 scen=C RF rmse=4.8807
Brad f1 scen=C XGB rmse=4.9461
Brad f1 scen=C MLP rmse=4.3792
Brad fold 2 ceiling rmse=2.9351
Brad f2 scen=A L7 rmse=2.9017
Brad f2 scen=A RF rmse=2.3137
Brad f2 scen=A XGB rmse=2.5308
Brad f2 scen=A MLP rmse=2.0073
Brad f2 scen=B L7 rmse=3.2585
Brad f2 scen=B RF rmse=2.5350
Brad f2 scen=B XGB rmse=2.7523
Brad f2 scen=B MLP rmse=2.7386
Brad f2 scen=C L7 rmse=3.8850
Brad f2 scen=C RF rmse=4.7324
Brad f2 scen=C XGB rmse=4.7753
Brad f2 scen=C MLP rmse=4.1180
Brad fold 3 ceiling rmse=3.4970
Brad f3 scen=A L7 rmse=3.4084
Brad f3 scen=A RF rmse=3.3466
Brad f3 scen=A XGB rmse=3.3244
Brad f3 scen=A MLP rmse=2.6848
Brad f3 scen=B L7 rmse=4.4551
Brad f3 scen=B RF rmse=3.5451
Brad f3 scen=B XGB rmse=3.5085
Brad f3 scen=B MLP rmse=2.9872
Brad f3 scen=C L7 rmse=5.2178
Brad f3 scen=C RF rmse=6.3727
Brad f3 scen=C XGB rmse=6.3673
Brad f3 scen=C MLP rmse=5.4942
Brad fold 4 ceiling rmse=3.0837
Brad f4 scen=A L7 rmse=3.2806
Brad f4 scen=A RF rmse=2.8092
Brad f4 scen=A XGB rmse=2.5629
Brad f4 scen=A MLP rmse=2.2576
Brad f4 scen=B L7 rmse=3.6093
Brad f4 scen=B RF rmse=2.8217
Brad f4 scen=B XGB rmse=2.7546
Brad f4 scen=B MLP rmse=2.5160
Brad f4 scen=C L7 rmse=4.1228
Brad f4 scen=C RF rmse=5.0091
Brad f4 scen=C XGB rmse=5.1108
Brad f4 scen=C MLP rmse=4.5622
Brad fold 5 ceiling rmse=2.3056
Brad f5 scen=A L7 rmse=2.5747
Brad f5 scen=A RF rmse=2.1654
Brad f5 scen=A XGB rmse=2.1488
Brad f5 scen=A MLP rmse=1.6440
Brad f5 scen=B L7 rmse=2.8395
Brad f5 scen=B RF rmse=2.1784
Brad f5 scen=B XGB rmse=1.9338
Brad f5 scen=B MLP rmse=1.7915
Brad f5 scen=C L7 rmse=3.4614
Brad f5 scen=C RF rmse=4.2453
Brad f5 scen=C XGB rmse=4.2664
Brad f5 scen=C MLP rmse=3.7416
Brad fold 6 ceiling rmse=3.4585
Brad f6 scen=A L7 rmse=3.6468
Brad f6 scen=A RF rmse=3.2372
Brad f6 scen=A XGB rmse=3.2437
Brad f6 scen=A MLP rmse=3.1791
Brad f6 scen=B L7 rmse=4.0334
Brad f6 scen=B RF rmse=3.3884
Brad f6 scen=B XGB rmse=3.2260
Brad f6 scen=B MLP rmse=3.1131
Brad f6 scen=C L7 rmse=4.6416
Brad f6 scen=C RF rmse=5.5942
Brad f6 scen=C XGB rmse=5.8362
Brad f6 scen=C MLP rmse=5.4286
Brad fold 7 ceiling rmse=3.0177
Brad f7 scen=A L7 rmse=3.7911
Brad f7 scen=A RF rmse=3.1650
Brad f7 scen=A XGB rmse=3.2414
Brad f7 scen=A MLP rmse=2.4484
Brad f7 scen=B L7 rmse=3.7669
Brad f7 scen=B RF rmse=3.2221
Brad f7 scen=B XGB rmse=2.9770
Brad f7 scen=B MLP rmse=2.4437
Brad f7 scen=C L7 rmse=4.1943
Brad f7 scen=C RF rmse=4.9651
Brad f7 scen=C XGB rmse=4.9186
Brad f7 scen=C MLP rmse=4.4649
Brad fold 8 ceiling rmse=2.5853
Brad f8 scen=A L7 rmse=3.0986
Brad f8 scen=A RF rmse=2.7236
Brad f8 scen=A XGB rmse=2.6644
Brad f8 scen=A MLP rmse=2.7841
Brad f8 scen=B L7 rmse=3.5040
Brad f8 scen=B RF rmse=2.8464
Brad f8 scen=B XGB rmse=2.8305
Brad f8 scen=B MLP rmse=3.0714
Brad f8 scen=C L7 rmse=4.0957
Brad f8 scen=C RF rmse=5.0794
Brad f8 scen=C XGB rmse=5.1655
Brad f8 scen=C MLP rmse=4.6777
Brad fold 9 ceiling rmse=3.6467
Brad f9 scen=A L7 rmse=3.5924
Brad f9 scen=A RF rmse=3.1688
Brad f9 scen=A XGB rmse=3.0234
Brad f9 scen=A MLP rmse=2.8304
Brad f9 scen=B L7 rmse=4.6273
Brad f9 scen=B RF rmse=3.3723
Brad f9 scen=B XGB rmse=3.3180
Brad f9 scen=B MLP rmse=3.2198
Brad f9 scen=C L7 rmse=5.3788
Brad f9 scen=C RF rmse=6.4780
Brad f9 scen=C XGB rmse=6.6138
Brad f9 scen=C MLP rmse=5.7526
Liberman fold 0 ceiling rmse=2.3353
Liberman f0 scen=A L7 rmse=4.5322
Liberman f0 scen=A RF rmse=4.9844
Liberman f0 scen=A XGB rmse=4.8778
Liberman f0 scen=A MLP rmse=4.1205
Liberman f0 scen=B L7 rmse=3.4396
Liberman f0 scen=B RF rmse=2.7403
Liberman f0 scen=B XGB rmse=2.6423
Liberman f0 scen=B MLP rmse=2.1211
Liberman f0 scen=C L7 rmse=2.8851
Liberman f0 scen=C RF rmse=2.3681
Liberman f0 scen=C XGB rmse=2.2144
Liberman f0 scen=C MLP rmse=2.1579
Liberman fold 1 ceiling rmse=2.4142
Liberman f1 scen=A L7 rmse=4.2907
Liberman f1 scen=A RF rmse=4.8410
Liberman f1 scen=A XGB rmse=4.9829
Liberman f1 scen=A MLP rmse=3.5436
Liberman f1 scen=B L7 rmse=3.2986
Liberman f1 scen=B RF rmse=2.4844
Liberman f1 scen=B XGB rmse=2.2491
Liberman f1 scen=B MLP rmse=2.0660
Liberman f1 scen=C L7 rmse=2.8437
Liberman f1 scen=C RF rmse=2.2468
Liberman f1 scen=C XGB rmse=2.1397
Liberman f1 scen=C MLP rmse=2.0581
Liberman fold 2 ceiling rmse=2.0305
Liberman f2 scen=A L7 rmse=4.1560
Liberman f2 scen=A RF rmse=4.5989
Liberman f2 scen=A XGB rmse=4.7102
Liberman f2 scen=A MLP rmse=3.8030
Liberman f2 scen=B L7 rmse=3.1649
Liberman f2 scen=B RF rmse=2.2525
Liberman f2 scen=B XGB rmse=2.3957
Liberman f2 scen=B MLP rmse=2.0388
Liberman f2 scen=C L7 rmse=2.6490
Liberman f2 scen=C RF rmse=1.9207
Liberman f2 scen=C XGB rmse=1.9543
Liberman f2 scen=C MLP rmse=1.9673
Liberman fold 3 ceiling rmse=1.9208
Liberman f3 scen=A L7 rmse=4.2094
Liberman f3 scen=A RF rmse=4.3830
Liberman f3 scen=A XGB rmse=4.4238
Liberman f3 scen=A MLP rmse=3.8914
Liberman f3 scen=B L7 rmse=3.5515
Liberman f3 scen=B RF rmse=2.9816
Liberman f3 scen=B XGB rmse=2.6031
Liberman f3 scen=B MLP rmse=2.5139
Liberman f3 scen=C L7 rmse=3.3658
Liberman f3 scen=C RF rmse=2.4690
Liberman f3 scen=C XGB rmse=2.4638
Liberman f3 scen=C MLP rmse=1.9602
Liberman fold 4 ceiling rmse=1.9278
Liberman f4 scen=A L7 rmse=3.6819
Liberman f4 scen=A RF rmse=3.4882
Liberman f4 scen=A XGB rmse=3.6850
Liberman f4 scen=A MLP rmse=2.9097
Liberman f4 scen=B L7 rmse=2.7767
Liberman f4 scen=B RF rmse=1.8926
Liberman f4 scen=B XGB rmse=1.8156
Liberman f4 scen=B MLP rmse=2.1014
Liberman f4 scen=C L7 rmse=2.4243
Liberman f4 scen=C RF rmse=1.4870
Liberman f4 scen=C XGB rmse=1.4787
Liberman f4 scen=C MLP rmse=1.8109
Liberman fold 5 ceiling rmse=2.6161
Liberman f5 scen=A L7 rmse=3.7659
Liberman f5 scen=A RF rmse=4.1359
Liberman f5 scen=A XGB rmse=4.3691
Liberman f5 scen=A MLP rmse=3.8194
Liberman f5 scen=B L7 rmse=3.2212
Liberman f5 scen=B RF rmse=2.9378
Liberman f5 scen=B XGB rmse=2.6814
Liberman f5 scen=B MLP rmse=3.0323
Liberman f5 scen=C L7 rmse=3.2831
Liberman f5 scen=C RF rmse=2.5711
Liberman f5 scen=C XGB rmse=2.7011
Liberman f5 scen=C MLP rmse=2.9060
Liberman fold 6 ceiling rmse=2.2738
Liberman f6 scen=A L7 rmse=3.6463
Liberman f6 scen=A RF rmse=3.4705
Liberman f6 scen=A XGB rmse=3.7296
Liberman f6 scen=A MLP rmse=2.9430
Liberman f6 scen=B L7 rmse=3.2451
Liberman f6 scen=B RF rmse=2.8685
Liberman f6 scen=B XGB rmse=2.6729
Liberman f6 scen=B MLP rmse=2.3798
Liberman f6 scen=C L7 rmse=3.3591
Liberman f6 scen=C RF rmse=2.2666
Liberman f6 scen=C XGB rmse=2.0992
Liberman f6 scen=C MLP rmse=1.9412
Liberman fold 7 ceiling rmse=2.7247
Liberman f7 scen=A L7 rmse=3.8568
Liberman f7 scen=A RF rmse=3.7971
Liberman f7 scen=A XGB rmse=4.1259
Liberman f7 scen=A MLP rmse=4.1659
Liberman f7 scen=B L7 rmse=3.3611
Liberman f7 scen=B RF rmse=3.1882
Liberman f7 scen=B XGB rmse=3.0443
Liberman f7 scen=B MLP rmse=2.8532
Liberman f7 scen=C L7 rmse=3.4791
Liberman f7 scen=C RF rmse=2.9184
Liberman f7 scen=C XGB rmse=2.9793
Liberman f7 scen=C MLP rmse=2.7119
Liberman fold 8 ceiling rmse=2.7868
Liberman f8 scen=A L7 rmse=4.3487
Liberman f8 scen=A RF rmse=4.6412
Liberman f8 scen=A XGB rmse=4.8778
Liberman f8 scen=A MLP rmse=4.4632
Liberman f8 scen=B L7 rmse=3.9273
Liberman f8 scen=B RF rmse=3.3228
Liberman f8 scen=B XGB rmse=3.2771
Liberman f8 scen=B MLP rmse=2.7475
Liberman f8 scen=C L7 rmse=4.0870
Liberman f8 scen=C RF rmse=2.9581
Liberman f8 scen=C XGB rmse=2.8364
Liberman f8 scen=C MLP rmse=2.7692
Liberman fold 9 ceiling rmse=2.3898
Liberman f9 scen=A L7 rmse=3.8859
Liberman f9 scen=A RF rmse=4.0356
Liberman f9 scen=A XGB rmse=4.1586
Liberman f9 scen=A MLP rmse=3.2398
Liberman f9 scen=B L7 rmse=2.9141
Liberman f9 scen=B RF rmse=2.4147
Liberman f9 scen=B XGB rmse=2.3142
Liberman f9 scen=B MLP rmse=2.4397
Liberman f9 scen=C L7 rmse=2.4942
Liberman f9 scen=C RF rmse=2.5927
Liberman f9 scen=C XGB rmse=2.6812
Liberman f9 scen=C MLP rmse=2.9562
/Users/nowaki027/MSDS/Practicum/figures/cache/stage2_synthesis_cv_summary.parquet
Synthesis CV: 5-fold → stage2_synthesis_cv_5fold_summary.parquet

=== Global Stage 1 (per training scenario A/B/C) ===
           Selected RF  — fit acc (animal@cal): 0.944 | non-test acc (animal@cal): 0.933 | threshold (Fit+Val): 0.423 | test acc (animal@cal): 0.917 | test acc@0.5: 0.583 | AUC: 0.944
  global S1 scen=A (RF): fit/val 45 animals, official test 12 animals, labels for 162 animals | Brad test acc=0.917 AUC=0.944 | Lib test acc=nan AUC=nan
           Selected RF  — fit acc (animal@cal): 0.865 | non-test acc (animal@cal): 0.860 | threshold (Fit+Val): 0.458 | test acc (animal@cal): 0.788 | test acc@0.5: 0.727 | AUC: 0.805
  global S1 scen=B (RF): fit/val 129 animals, official test 33 animals, labels for 162 animals | Brad test acc=0.833 AUC=0.722 | Lib test acc=0.762 AUC=0.918
           Selected RF  — fit acc (animal@cal): 0.971 | non-test acc (animal@cal): 0.940 | threshold (Fit+Val): 0.556 | test acc (animal@cal): 0.952 | test acc@0.5: 0.810 | AUC: 0.909
  global S1 scen=C (RF): fit/val 84 animals, official test 21 animals, labels for 162 animals | Brad test acc=nan AUC=nan | Lib test acc=0.952 AUC=0.909
Brad fold 0 ceiling rmse=2.8246
Brad f0 scen=A L7 rmse=3.2141
Brad f0 scen=A RF rmse=2.7505
Brad f0 scen=A XGB rmse=2.6586
Brad f0 scen=A MLP rmse=2.2033
Brad f0 scen=B L7 rmse=3.4193
Brad f0 scen=B RF rmse=2.8378
Brad f0 scen=B XGB rmse=2.6865
Brad f0 scen=B MLP rmse=2.2422
Brad f0 scen=C L7 rmse=3.8892
Brad f0 scen=C RF rmse=4.6921
Brad f0 scen=C XGB rmse=4.7661
Brad f0 scen=C MLP rmse=4.2288
Brad fold 1 ceiling rmse=3.3734
Brad f1 scen=A L7 rmse=3.2879
Brad f1 scen=A RF rmse=2.7971
Brad f1 scen=A XGB rmse=2.9447
Brad f1 scen=A MLP rmse=2.4119
Brad f1 scen=B L7 rmse=4.0018
Brad f1 scen=B RF rmse=3.1597
Brad f1 scen=B XGB rmse=3.0872
Brad f1 scen=B MLP rmse=2.6878
Brad f1 scen=C L7 rmse=4.5943
Brad f1 scen=C RF rmse=5.6346
Brad f1 scen=C XGB rmse=5.7575
Brad f1 scen=C MLP rmse=5.3476
Brad fold 2 ceiling rmse=2.9079
Brad f2 scen=A L7 rmse=3.5521
Brad f2 scen=A RF rmse=3.0554
Brad f2 scen=A XGB rmse=3.0184
Brad f2 scen=A MLP rmse=2.9840
Brad f2 scen=B L7 rmse=4.0997
Brad f2 scen=B RF rmse=3.2659
Brad f2 scen=B XGB rmse=3.2483
Brad f2 scen=B MLP rmse=3.0750
Brad f2 scen=C L7 rmse=4.6106
Brad f2 scen=C RF rmse=5.4622
Brad f2 scen=C XGB rmse=5.4888
Brad f2 scen=C MLP rmse=5.0843
Brad fold 3 ceiling rmse=2.5712
Brad f3 scen=A L7 rmse=3.1855
Brad f3 scen=A RF rmse=2.9327
Brad f3 scen=A XGB rmse=2.8786
Brad f3 scen=A MLP rmse=2.0188
Brad f3 scen=B L7 rmse=3.6049
Brad f3 scen=B RF rmse=2.9524
Brad f3 scen=B XGB rmse=2.6140
Brad f3 scen=B MLP rmse=2.2182
Brad f3 scen=C L7 rmse=4.1826
Brad f3 scen=C RF rmse=5.0700
Brad f3 scen=C XGB rmse=5.0656
Brad f3 scen=C MLP rmse=4.5100
Brad fold 4 ceiling rmse=2.9512
Brad f4 scen=A L7 rmse=3.1108
Brad f4 scen=A RF rmse=2.6216
Brad f4 scen=A XGB rmse=2.6194
Brad f4 scen=A MLP rmse=2.3487
Brad f4 scen=B L7 rmse=3.4601
Brad f4 scen=B RF rmse=2.7157
Brad f4 scen=B XGB rmse=2.5487
Brad f4 scen=B MLP rmse=2.5293
Brad f4 scen=C L7 rmse=4.0395
Brad f4 scen=C RF rmse=4.9697
Brad f4 scen=C XGB rmse=5.1644
Brad f4 scen=C MLP rmse=4.3781
Liberman fold 0 ceiling rmse=2.2397
Liberman f0 scen=A L7 rmse=4.0145
Liberman f0 scen=A RF rmse=4.3108
Liberman f0 scen=A XGB rmse=4.3147
Liberman f0 scen=A MLP rmse=3.4712
Liberman f0 scen=B L7 rmse=3.1925
Liberman f0 scen=B RF rmse=2.6382
Liberman f0 scen=B XGB rmse=2.5927
Liberman f0 scen=B MLP rmse=2.3921
Liberman f0 scen=C L7 rmse=2.8883
Liberman f0 scen=C RF rmse=2.2335
Liberman f0 scen=C XGB rmse=2.2130
Liberman f0 scen=C MLP rmse=2.1206
Liberman fold 1 ceiling rmse=2.6214
Liberman f1 scen=A L7 rmse=3.7800
Liberman f1 scen=A RF rmse=4.0092
Liberman f1 scen=A XGB rmse=4.2960
Liberman f1 scen=A MLP rmse=3.9306
Liberman f1 scen=B L7 rmse=3.2841
Liberman f1 scen=B RF rmse=2.8473
Liberman f1 scen=B XGB rmse=2.6962
Liberman f1 scen=B MLP rmse=2.5200
Liberman f1 scen=C L7 rmse=3.2247
Liberman f1 scen=C RF rmse=2.4837
Liberman f1 scen=C XGB rmse=2.4415
Liberman f1 scen=C MLP rmse=2.4781
Liberman fold 2 ceiling rmse=2.4843
Liberman f2 scen=A L7 rmse=4.2842
Liberman f2 scen=A RF rmse=4.6931
Liberman f2 scen=A XGB rmse=4.8082
Liberman f2 scen=A MLP rmse=4.3756
Liberman f2 scen=B L7 rmse=3.6078
Liberman f2 scen=B RF rmse=3.0066
Liberman f2 scen=B XGB rmse=2.9227
Liberman f2 scen=B MLP rmse=2.4120
Liberman f2 scen=C L7 rmse=3.4867
Liberman f2 scen=C RF rmse=2.7489
Liberman f2 scen=C XGB rmse=2.6375
Liberman f2 scen=C MLP rmse=2.4108
Liberman fold 3 ceiling rmse=2.2991
Liberman f3 scen=A L7 rmse=3.8337
Liberman f3 scen=A RF rmse=3.8101
Liberman f3 scen=A XGB rmse=4.0382
Liberman f3 scen=A MLP rmse=3.4715
Liberman f3 scen=B L7 rmse=3.2462
Liberman f3 scen=B RF rmse=2.7732
Liberman f3 scen=B XGB rmse=2.5991
Liberman f3 scen=B MLP rmse=2.4535
Liberman f3 scen=C L7 rmse=3.2305
Liberman f3 scen=C RF rmse=2.3846
Liberman f3 scen=C XGB rmse=2.4579
Liberman f3 scen=C MLP rmse=2.2936
Liberman fold 4 ceiling rmse=1.9289
Liberman f4 scen=A L7 rmse=4.2902
Liberman f4 scen=A RF rmse=4.4348
Liberman f4 scen=A XGB rmse=4.5594
Liberman f4 scen=A MLP rmse=3.6750
Liberman f4 scen=B L7 rmse=3.3080
Liberman f4 scen=B RF rmse=2.4454
Liberman f4 scen=B XGB rmse=2.2338
Liberman f4 scen=B MLP rmse=2.3602
Liberman f4 scen=C L7 rmse=2.7295
Liberman f4 scen=C RF rmse=2.0512
Liberman f4 scen=C XGB rmse=2.0378
Liberman f4 scen=C MLP rmse=2.2022
/Users/nowaki027/MSDS/Practicum/figures/cache/stage2_synthesis_cv_5fold_summary.parquet

    test_set scenario        model      RMSE  RMSE_sem     source  n_folds
0       Brad      all      ceiling  2.961628  0.149565    ceiling       10
1   Liberman      all      ceiling  2.341969  0.098753    ceiling       10
2       Brad        A  LR baseline  3.284766  0.114825  classical       10
3       Brad        A           RF  2.795391  0.137717  classical       10
4       Brad        A          XGB  2.728043  0.145813  classical       10
5       Brad        A          MLP  2.386861  0.165069         nn       10
6       Brad        B  LR baseline  3.673654  0.182984  classical       10
7       Brad        B           RF  2.945283  0.144924  classical       10
8       Brad        B          XGB  2.836683  0.157263  classical       10
9       Brad        B          MLP  2.586836  0.169115         nn       10
10      Brad        C  LR baseline  4.243655  0.210388  classical       10
11      Brad        C           RF  5.138148  0.254856  classical       10
12      Brad        C          XGB  5.224184  0.255678  classical       10
13      Brad        C          MLP  4.604082  0.241428         nn       10
14  Liberman        A  LR baseline  4.037380  0.097651  classical       10
15  Liberman        A           RF  4.237575  0.170997  classical       10
16  Liberman        A          XGB  4.394067  0.148616  classical       10
17  Liberman        A          MLP  3.689947  0.165689         nn       10
18  Liberman        B  LR baseline  3.289999  0.101610  classical       10
19  Liberman        B           RF  2.708352  0.140298  classical       10
20  Liberman        B          XGB  2.569561  0.130055  classical       10
21  Liberman        B          MLP  2.429361  0.112607         nn       10
22  Liberman        C  LR baseline  3.087038  0.164195  classical       10
23  Liberman        C           RF  2.379836  0.139553  classical       10
24  Liberman        C          XGB  2.354821  0.146044  classical       10
25  Liberman        C          MLP  2.323897  0.143558         nn       10

In [4]:
summary_5

    test_set scenario        model      RMSE  RMSE_sem     source  n_folds
0       Brad      all      ceiling  2.925654  0.129869    ceiling        5
1   Liberman      all      ceiling  2.314670  0.117805    ceiling        5
2       Brad        A  LR baseline  3.270088  0.075996  classical        5
3       Brad        A           RF  2.831451  0.074894  classical        5
4       Brad        A          XGB  2.823922  0.078911  classical        5
5       Brad        A          MLP  2.393371  0.162426         nn        5
6       Brad        B  LR baseline  3.717164  0.140497  classical        5
7       Brad        B           RF  2.986284  0.101157  classical        5
8       Brad        B          XGB  2.836939  0.139167  classical        5
9       Brad        B          MLP  2.550488  0.158097         nn        5
10      Brad        C  LR baseline  4.263235  0.146083  classical        5
11      Brad        C           RF  5.165726  0.170227  classical        5
12      Brad        C          XGB  5.248483  0.171774  classical        5
13      Brad        C          MLP  4.709754  0.215452         nn        5
14  Liberman        A  LR baseline  4.040516  0.107941  classical        5
15  Liberman        A           RF  4.251620  0.155834  classical        5
16  Liberman        A          XGB  4.403292  0.130575  classical        5
17  Liberman        A          MLP  3.784798  0.170127         nn        5
18  Liberman        B  LR baseline  3.327729  0.072688  classical        5
19  Liberman        B           RF  2.742136  0.095088  classical        5
20  Liberman        B          XGB  2.608875  0.111159  classical        5
21  Liberman        B          MLP  2.427549  0.027609         nn        5
22  Liberman        C  LR baseline  3.111915  0.134817  classical        5
23  Liberman        C           RF  2.380376  0.117561  classical        5
24  Liberman        C          XGB  2.357537  0.104546  classical        5
25  Liberman        C          MLP  2.301046  0.065496         nn        5

In [5]:
# Ceiling sanity: Liberman vs cached baseline; Brad inline recompute
STRATUM_COLS = ["noise_cat", "frequency"]
data = load_nn_stage2_data()
lib_cv = eval_stratum_mean_baseline_cv(
    data.reformatted_orig.reset_index(drop=True), STRATUM_COLS
)
lib_ref = pd.read_parquet(LIBERMAN_GROUP_MEAN_BASELINE_PARQUET)
print("Liberman CV rmse", lib_cv["rmse"], "±", lib_cv["rmse_sem"])
print(
    "Liberman parquet rmse",
    float(lib_ref["rmse"].iloc[0]),
    "±",
    float(lib_ref["rmse_sem"].iloc[0]),
)
brad_cv = eval_stratum_mean_baseline_cv(
    data.reformatted.reset_index(drop=True), STRATUM_COLS
)
print("Brad inline CV rmse", brad_cv["rmse"], "±", brad_cv["rmse_sem"])
for n_folds, summary in summaries.items():
    print(f"\n=== {n_folds}-fold ceiling (from synthesis summary) ===")
    print(summary.loc[summary["model"].eq("ceiling")])

Liberman CV rmse 2.3419685439445384 ± 0.09875276799742796
Liberman parquet rmse 2.3419685439445384 ± 0.09875276799742796
Brad inline CV rmse 2.9616282300167436 ± 0.14956470965710605

=== 10-fold ceiling (from synthesis summary) ===
   test_set scenario    model      RMSE  RMSE_sem   source  n_folds
0      Brad      all  ceiling  2.961628  0.149565  ceiling       10
1  Liberman      all  ceiling  2.341969  0.098753  ceiling       10

=== 5-fold ceiling (from synthesis summary) ===
   test_set scenario    model      RMSE  RMSE_sem   source  n_folds
0      Brad      all  ceiling  2.925654  0.129869  ceiling        5
1  Liberman      all  ceiling  2.314670  0.117805  ceiling        5

In [6]:
for n_folds, summary in summaries.items():
    png = synthesis_act4_grid_cv(summary, n_folds=n_folds)
    print(f"{n_folds}-fold saved", png)

10-fold saved /Users/nowaki027/MSDS/Practicum/figures/presentation/deck_act4_synthesis_grid_RMSE_cv.png
5-fold saved /Users/nowaki027/MSDS/Practicum/figures/presentation/deck_act4_synthesis_grid_RMSE_cv_5fold.png

## Panel C — pooled holdout RMSE (both cohorts per fold)

Recomputes animal×frequency RMSE by concatenating Brad + Liberman eval aggs per fold (not the mean of cohort fold RMSEs). Pooled rows use **`scenario` 1 / 2 / 3** = within-cohort / cross-cohort / combined (distinct from per-cohort train-slice **A / B / C**). Review the table before running the 3-panel figure below.

In [8]:
FORCE_POOLED_RERUN = True
pooled_folds = compute_pooled_synthesis_folds(
    hp, device=device, verbose=True, force_rerun=FORCE_POOLED_RERUN
)
summary_pooled = summarize_pooled_folds(pooled_folds)
display(panel_c_rmse_report_table(summary_pooled))
summary_10_pooled = pd.concat([summary_10, summary_pooled], ignore_index=True)
display(summary_10_pooled.loc[summary_10_pooled["test_set"].eq("Pooled")])

Pooled synthesis CV: 10-fold → stage2_synthesis_cv_pooled_folds.parquet
pooled fold 0 ceiling rmse=2.5794
pooled f0 display=1 L7 rmse=3.0256
pooled f0 display=1 RF rmse=2.3231
pooled f0 display=1 XGB rmse=2.1444
pooled f0 display=1 MLP rmse=1.9836
pooled f0 display=2 L7 rmse=4.1174
pooled f0 display=2 RF rmse=4.6359
pooled f0 display=2 XGB rmse=4.6415
pooled f0 display=2 MLP rmse=4.2921
pooled f0 display=3 L7 rmse=3.2763
pooled f0 display=3 RF rmse=2.6244
pooled f0 display=3 XGB rmse=2.4497
pooled f0 display=3 MLP rmse=1.8790
pooled fold 1 ceiling rmse=2.6754
pooled f1 display=1 L7 rmse=3.0518
pooled f1 display=1 RF rmse=2.4816
pooled f1 display=1 XGB rmse=2.3030
pooled f1 display=1 MLP rmse=2.3499
pooled f1 display=2 L7 rmse=4.2034
pooled f1 display=2 RF rmse=4.8577
pooled f1 display=2 XGB rmse=4.9675
pooled f1 display=2 MLP rmse=4.0887
pooled f1 display=3 L7 rmse=3.4468
pooled f1 display=3 RF rmse=2.7655
pooled f1 display=3 XGB rmse=2.5694
pooled f1 display=3 MLP rmse=2.0671
pooled fold 2 ceiling rmse=2.5708
pooled f2 display=1 L7 rmse=2.7433
pooled f2 display=1 RF rmse=2.0719
pooled f2 display=1 XGB rmse=2.1810
pooled f2 display=1 MLP rmse=1.8873
pooled f2 display=2 L7 rmse=4.0598
pooled f2 display=2 RF rmse=4.6477
pooled f2 display=2 XGB rmse=4.7339
pooled f2 display=2 MLP rmse=3.9795
pooled f2 display=3 L7 rmse=3.1992
pooled f2 display=3 RF rmse=2.3589
pooled f2 display=3 XGB rmse=2.5308
pooled f2 display=3 MLP rmse=2.3745
pooled fold 3 ceiling rmse=2.8030
pooled f3 display=1 L7 rmse=3.3817
pooled f3 display=1 RF rmse=2.8270
pooled f3 display=1 XGB rmse=2.8143
pooled f3 display=1 MLP rmse=2.2600
pooled f3 display=2 L7 rmse=4.6097
pooled f3 display=2 RF rmse=5.2115
pooled f3 display=2 XGB rmse=5.2307
pooled f3 display=2 MLP rmse=4.3737
pooled f3 display=3 L7 rmse=3.9116
pooled f3 display=3 RF rmse=3.2025
pooled f3 display=3 XGB rmse=2.9718
pooled f3 display=3 MLP rmse=2.7026
pooled fold 4 ceiling rmse=2.3785
pooled f4 display=1 L7 rmse=2.7274
pooled f4 display=1 RF rmse=2.0067
pooled f4 display=1 XGB rmse=1.8939
pooled f4 display=1 MLP rmse=1.9686
pooled f4 display=2 L7 rmse=3.8283
pooled f4 display=2 RF rmse=4.0370
pooled f4 display=2 XGB rmse=4.1937
pooled f4 display=2 MLP rmse=3.5306
pooled f4 display=3 L7 rmse=3.0674
pooled f4 display=3 RF rmse=2.2320
pooled f4 display=3 XGB rmse=2.1605
pooled f4 display=3 MLP rmse=2.1986
pooled fold 5 ceiling rmse=2.7599
pooled f5 display=1 L7 rmse=3.0434
pooled f5 display=1 RF rmse=2.4307
pooled f5 display=1 XGB rmse=2.5134
pooled f5 display=1 MLP rmse=2.5284
pooled f5 display=2 L7 rmse=3.6576
pooled f5 display=2 RF rmse=4.1762
pooled f5 display=2 XGB rmse=4.3319
pooled f5 display=2 MLP rmse=3.8814
pooled f5 display=3 L7 rmse=3.0872
pooled f5 display=3 RF rmse=2.6854
pooled f5 display=3 XGB rmse=2.4350
pooled f5 display=3 MLP rmse=2.6231
pooled fold 6 ceiling rmse=3.0510
pooled f6 display=1 L7 rmse=3.4694
pooled f6 display=1 RF rmse=2.6708
pooled f6 display=1 XGB rmse=2.5868
pooled f6 display=1 MLP rmse=2.4695
pooled f6 display=2 L7 rmse=4.0469
pooled f6 display=2 RF rmse=4.3860
pooled f6 display=2 XGB rmse=4.6303
pooled f6 display=2 MLP rmse=4.1942
pooled f6 display=3 L7 rmse=3.5601
pooled f6 display=3 RF rmse=3.0731
pooled f6 display=3 XGB rmse=2.8919
pooled f6 display=3 MLP rmse=2.6550
pooled fold 7 ceiling rmse=2.9614
pooled f7 display=1 L7 rmse=3.6033
pooled f7 display=1 RF rmse=3.0164
pooled f7 display=1 XGB rmse=3.0836
pooled f7 display=1 MLP rmse=2.5911
pooled f7 display=2 L7 rmse=3.9911
pooled f7 display=2 RF rmse=4.2879
pooled f7 display=2 XGB rmse=4.4501
pooled f7 display=2 MLP rmse=4.1239
pooled f7 display=3 L7 rmse=3.5240
pooled f7 display=3 RF rmse=3.2013
pooled f7 display=3 XGB rmse=3.0184
pooled f7 display=3 MLP rmse=2.6080
pooled fold 8 ceiling rmse=2.7604
pooled f8 display=1 L7 rmse=3.7494
pooled f8 display=1 RF rmse=2.8730
pooled f8 display=1 XGB rmse=2.7736
pooled f8 display=1 MLP rmse=2.8304
pooled f8 display=2 L7 rmse=4.2562
pooled f8 display=2 RF rmse=4.8091
pooled f8 display=2 XGB rmse=4.9869
pooled f8 display=2 MLP rmse=4.3589
pooled f8 display=3 L7 rmse=3.7751
pooled f8 display=3 RF rmse=3.1538
pooled f8 display=3 XGB rmse=3.1182
pooled f8 display=3 MLP rmse=2.8225
pooled fold 9 ceiling rmse=3.0186
pooled f9 display=1 L7 rmse=2.9028
pooled f9 display=1 RF rmse=2.7959
pooled f9 display=1 XGB rmse=2.7987
pooled f9 display=1 MLP rmse=2.8733
pooled f9 display=2 L7 rmse=4.4343
pooled f9 display=2 RF rmse=4.9757
pooled f9 display=2 XGB rmse=5.1009
pooled f9 display=2 MLP rmse=4.4489
pooled f9 display=3 L7 rmse=3.5713
pooled f9 display=3 RF rmse=2.7675
pooled f9 display=3 XGB rmse=2.6871
pooled f9 display=3 MLP rmse=2.7737

                    model    Within-cohort     Cross-cohort         Combined
0             LR baseline  3.1698 ± 0.1134  4.1205 ± 0.0875  3.4419 ± 0.0895
1                      RF  2.5497 ± 0.1089  4.6025 ± 0.1187  2.8064 ± 0.1098
2                     XGB  2.5093 ± 0.1176  4.7267 ± 0.1082  2.6833 ± 0.0974
3                     MLP  2.3742 ± 0.1108  4.1272 ± 0.0875  2.4704 ± 0.1023
4  ceiling (stratum mean)                                    2.7558 ± 0.0679

   test_set scenario        model      RMSE  RMSE_sem     source  n_folds
26   Pooled      all      ceiling  2.755841  0.067898    ceiling       10
27   Pooled        A  LR baseline  3.169794  0.113435  classical       10
28   Pooled        A           RF  2.549694  0.108926  classical       10
29   Pooled        A          XGB  2.509282  0.117596  classical       10
30   Pooled        A          MLP  2.374202  0.110806         nn       10
31   Pooled        B  LR baseline  4.120477  0.087476  classical       10
32   Pooled        B           RF  4.602473  0.118718  classical       10
33   Pooled        B          XGB  4.726730  0.108156  classical       10
34   Pooled        B          MLP  4.127185  0.087519         nn       10
35   Pooled        C  LR baseline  3.441903  0.089532  classical       10
36   Pooled        C           RF  2.806440  0.109843  classical       10
37   Pooled        C          XGB  2.683281  0.097411  classical       10
38   Pooled        C          MLP  2.470404  0.102287         nn       10

In [9]:
png = synthesis_cohort_panels_cv(summary_10)
svg = png.with_suffix(".svg")
print("10-fold cohort panels saved", png, "+", svg)

10-fold cohort panels saved /Users/nowaki027/MSDS/Practicum/figures/presentation/deck_act4_synthesis_cohorts_RMSE_cv.png + /Users/nowaki027/MSDS/Practicum/figures/presentation/deck_act4_synthesis_cohorts_RMSE_cv.svg

In [10]:
png3 = synthesis_cohort_panels_3cv(summary_10_pooled)
svg3 = png3.with_suffix(".svg")
print("10-fold 3-panel cohort figure saved", png3, "+", svg3)

10-fold 3-panel cohort figure saved /Users/nowaki027/MSDS/Practicum/figures/presentation/deck_act4_synthesis_cohorts_RMSE_cv_3panel.png + /Users/nowaki027/MSDS/Practicum/figures/presentation/deck_act4_synthesis_cohorts_RMSE_cv_3panel.svg

## §5.2.2 — Pooled out-of-fold R² + Supplementary Figure S2

Backfills OOF prediction caches (separate progress from RMSE). Pooled OOF uses the same `compute_pooled_synthesis_folds` protocol as Panel C (not a Liberman+Brad concat).

In [11]:
# OOF backfill: reuses RMSE cache keys; only missing OOF rows are recomputed.
FORCE_OOF_RERUN = False
if FORCE_OOF_RERUN:
    from utils.stage2_synthesis_cv import (
        reset_pooled_oof_cache,
        reset_synthesis_oof_cache,
    )

    reset_synthesis_oof_cache()
    reset_pooled_oof_cache()

_, _ = run_synthesis_cv(hp, device=device, verbose=True, force_rerun=False)
pooled_folds = compute_pooled_synthesis_folds(
    hp, device=device, verbose=True, force_rerun=False
)

cohort_oof = pd.read_parquet(STAGE2_SYNTHESIS_CV_OOF_PARQUET)
pooled_oof = pd.read_parquet(STAGE2_SYNTHESIS_CV_POOLED_OOF_PARQUET)
print(
    "cohort OOF rows:", len(cohort_oof), "| pooled OOF rows:", len(pooled_oof)
)

r2_summary_fig = summarize_pooled_oof_r2(cohort_oof, pooled_oof)
display(pooled_oof_r2_report_table(r2_summary_fig))
r2_summary_fig.to_parquet(
    STAGE2_SYNTHESIS_CV_OOF_R2_SUMMARY_PARQUET, index=False
)
print("saved", STAGE2_SYNTHESIS_CV_OOF_R2_SUMMARY_PARQUET)

Synthesis CV: 10-fold → stage2_synthesis_cv_summary.parquet

=== Global Stage 1 (per training scenario A/B/C) ===
           Selected RF  — fit acc (animal@cal): 0.944 | non-test acc (animal@cal): 0.933 | threshold (Fit+Val): 0.423 | test acc (animal@cal): 0.917 | test acc@0.5: 0.583 | AUC: 0.944
  global S1 scen=A (RF): fit/val 45 animals, official test 12 animals, labels for 162 animals | Brad test acc=0.917 AUC=0.944 | Lib test acc=nan AUC=nan
           Selected RF  — fit acc (animal@cal): 0.865 | non-test acc (animal@cal): 0.860 | threshold (Fit+Val): 0.458 | test acc (animal@cal): 0.788 | test acc@0.5: 0.727 | AUC: 0.805
  global S1 scen=B (RF): fit/val 129 animals, official test 33 animals, labels for 162 animals | Brad test acc=0.833 AUC=0.722 | Lib test acc=0.762 AUC=0.918
           Selected RF  — fit acc (animal@cal): 0.971 | non-test acc (animal@cal): 0.940 | threshold (Fit+Val): 0.556 | test acc (animal@cal): 0.952 | test acc@0.5: 0.810 | AUC: 0.909
  global S1 scen=C (RF): fit/val 84 animals, official test 21 animals, labels for 162 animals | Brad test acc=nan AUC=nan | Lib test acc=0.952 AUC=0.909
Pooled synthesis CV: 10-fold → stage2_synthesis_cv_pooled_folds.parquet
cohort OOF rows: 25376 | pooled OOF rows: 12688

,model,Cohort A (Liberman),Cohort B (Brad),Pooled
0,LR baseline,Within-cohort: -0.4769; Cross-cohort: 0.0069; ...,Within-cohort: 0.3923; Cross-cohort: 0.2234; C...,Within-cohort: 0.3216; Cross-cohort: -0.1352; ...
1,RF,Within-cohort: -0.6384; Cross-cohort: 0.3194; ...,Within-cohort: 0.5498; Cross-cohort: 0.4991; C...,Within-cohort: 0.5585; Cross-cohort: -0.4195; ...
2,XGB,Within-cohort: -0.7546; Cross-cohort: 0.3857; ...,Within-cohort: 0.5610; Cross-cohort: 0.5396; C...,Within-cohort: 0.5707; Cross-cohort: -0.4946; ...
3,MLP,Within-cohort: -0.2061; Cross-cohort: 0.4979; ...,Within-cohort: 0.6697; Cross-cohort: 0.6251; C...,Within-cohort: 0.6278; Cross-cohort: -0.1045; ...
4,ceiling (stratum mean),0.5041 ± 0.0540,0.5091 ± 0.0381,0.4920 ± 0.0201

saved /Users/nowaki027/MSDS/Practicum/figures/cache/stage2_synthesis_cv_oof_r2_summary.parquet

In [12]:
png_s2 = synthesis_cohort_panels_3cv_r2(r2_summary_fig)
svg_s2 = png_s2.with_suffix(".svg")
print("Supplementary Figure S2 saved", png_s2, "+", svg_s2)

Supplementary Figure S2 saved /Users/nowaki027/MSDS/Practicum/figures/presentation/supplementary_figure_S2_pooled_oof_r2.png + /Users/nowaki027/MSDS/Practicum/figures/presentation/supplementary_figure_S2_pooled_oof_r2.svg

In [13]:
# 5-fold vs 10-fold RMSE (Liberman scenario C highlighted)
key = ["test_set", "scenario", "model"]
cmp = summary_10.merge(summary_5, on=key, suffixes=("_10", "_5"))
cmp["RMSE_delta_5_minus_10"] = cmp["RMSE_5"] - cmp["RMSE_10"]
cols = key + [
    "RMSE_10",
    "RMSE_sem_10",
    "RMSE_5",
    "RMSE_sem_5",
    "RMSE_delta_5_minus_10",
]
display(cmp[cols].sort_values(["test_set", "scenario", "model"]))

lib_c = cmp.loc[
    cmp["test_set"].eq("Liberman")
    & cmp["scenario"].eq("C")
    & cmp["model"].eq("RF")
]
if len(lib_c):
    r = lib_c.iloc[0]
    print(
        f"Liberman C RF: 10-fold {r.RMSE_10:.3f} ± {r.RMSE_sem_10:.3f} | "
        f"5-fold {r.RMSE_5:.3f} ± {r.RMSE_sem_5:.3f}"
    )

,test_set,scenario,model,RMSE_10,RMSE_sem_10,RMSE_5,RMSE_sem_5,RMSE_delta_5_minus_10
2,Brad,A,LR baseline,3.284766,0.114825,3.270088,0.075996,-0.014678
5,Brad,A,MLP,2.386861,0.165069,2.393371,0.162426,0.006509
3,Brad,A,RF,2.795391,0.137717,2.831451,0.074894,0.036060
4,Brad,A,XGB,2.728043,0.145813,2.823922,0.078911,0.095879
6,Brad,B,LR baseline,3.673654,0.182984,3.717164,0.140497,0.043510
9,Brad,B,MLP,2.586836,0.169115,2.550488,0.158097,-0.036347
7,Brad,B,RF,2.945283,0.144924,2.986284,0.101157,0.041001
8,Brad,B,XGB,2.836683,0.157263,2.836939,0.139167,0.000256
10,Brad,C,LR baseline,4.243655,0.210388,4.263235,0.146083,0.019581
13,Brad,C,MLP,4.604082,0.241428,4.709754,0.215452,0.105672
11,Brad,C,RF,5.138148,0.254856,5.165726,0.170227,0.027578
12,Brad,C,XGB,5.224184,0.255678,5.248483,0.171774,0.024298
0,Brad,all,ceiling,2.961628,0.149565,2.925654,0.129869,-0.035975
14,Liberman,A,LR baseline,4.037380,0.097651,4.040516,0.107941,0.003137
17,Liberman,A,MLP,3.689947,0.165689,3.784798,0.170127,0.094851
15,Liberman,A,RF,4.237575,0.170997,4.251620,0.155834,0.014045
16,Liberman,A,XGB,4.394067,0.148616,4.403292,0.130575,0.009224
18,Liberman,B,LR baseline,3.289999,0.101610,3.327729,0.072688,0.037730
21,Liberman,B,MLP,2.429361,0.112607,2.427549,0.027609,-0.001811
19,Liberman,B,RF,2.708352,0.140298,2.742136,0.095088,0.033784
20,Liberman,B,XGB,2.569561,0.130055,2.608875,0.111159,0.039313
22,Liberman,C,LR baseline,3.087038,0.164195,3.111915,0.134817,0.024878
25,Liberman,C,MLP,2.323897,0.143558,2.301046,0.065496,-0.022851
23,Liberman,C,RF,2.379836,0.139553,2.380376,0.117561,0.000539
24,Liberman,C,XGB,2.354821,0.146044,2.357537,0.104546,0.002716
1,Liberman,all,ceiling,2.341969,0.098753,2.314670,0.117805,-0.027299

Liberman C RF: 10-fold 2.380 ± 0.140 | 5-fold 2.380 ± 0.118

In [14]:
# Act IV-style digest (mean ± SEM)
for n_folds, summary in summaries.items():
    print(f"\n######## {n_folds}-fold ########")
    for ts in ("Brad", "Liberman"):
        for scen in ("A", "B", "C"):
            sub = summary.loc[
                summary["test_set"].eq(ts) & summary["scenario"].eq(scen)
            ]
            print(f"\n=== {ts} test | train {scen} ===")
            print(
                sub[["model", "RMSE", "RMSE_sem", "source"]].to_string(
                    index=False
                )
            )

######## 10-fold ########

=== Brad test | train A ===
      model     RMSE  RMSE_sem    source
LR baseline 3.284766  0.114825 classical
         RF 2.795391  0.137717 classical
        XGB 2.728043  0.145813 classical
        MLP 2.386861  0.165069        nn

=== Brad test | train B ===
      model     RMSE  RMSE_sem    source
LR baseline 3.673654  0.182984 classical
         RF 2.945283  0.144924 classical
        XGB 2.836683  0.157263 classical
        MLP 2.586836  0.169115        nn

=== Brad test | train C ===
      model     RMSE  RMSE_sem    source
LR baseline 4.243655  0.210388 classical
         RF 5.138148  0.254856 classical
        XGB 5.224184  0.255678 classical
        MLP 4.604082  0.241428        nn

=== Liberman test | train A ===
      model     RMSE  RMSE_sem    source
LR baseline 4.037380  0.097651 classical
         RF 4.237575  0.170997 classical
        XGB 4.394067  0.148616 classical
        MLP 3.689947  0.165689        nn

=== Liberman test | train B ===
      model     RMSE  RMSE_sem    source
LR baseline 3.289999  0.101610 classical
         RF 2.708352  0.140298 classical
        XGB 2.569561  0.130055 classical
        MLP 2.429361  0.112607        nn

=== Liberman test | train C ===
      model     RMSE  RMSE_sem    source
LR baseline 3.087038  0.164195 classical
         RF 2.379836  0.139553 classical
        XGB 2.354821  0.146044 classical
        MLP 2.323897  0.143558        nn

######## 5-fold ########

=== Brad test | train A ===
      model     RMSE  RMSE_sem    source
LR baseline 3.270088  0.075996 classical
         RF 2.831451  0.074894 classical
        XGB 2.823922  0.078911 classical
        MLP 2.393371  0.162426        nn

=== Brad test | train B ===
      model     RMSE  RMSE_sem    source
LR baseline 3.717164  0.140497 classical
         RF 2.986284  0.101157 classical
        XGB 2.836939  0.139167 classical
        MLP 2.550488  0.158097        nn

=== Brad test | train C ===
      model     RMSE  RMSE_sem    source
LR baseline 4.263235  0.146083 classical
         RF 5.165726  0.170227 classical
        XGB 5.248483  0.171774 classical
        MLP 4.709754  0.215452        nn

=== Liberman test | train A ===
      model     RMSE  RMSE_sem    source
LR baseline 4.040516  0.107941 classical
         RF 4.251620  0.155834 classical
        XGB 4.403292  0.130575 classical
        MLP 3.784798  0.170127        nn

=== Liberman test | train B ===
      model     RMSE  RMSE_sem    source
LR baseline 3.327729  0.072688 classical
         RF 2.742136  0.095088 classical
        XGB 2.608875  0.111159 classical
        MLP 2.427549  0.027609        nn

=== Liberman test | train C ===
      model     RMSE  RMSE_sem    source
LR baseline 3.111915  0.134817 classical
         RF 2.380376  0.117561 classical
        XGB 2.357537  0.104546 classical
        MLP 2.301046  0.065496        nn

In [ ]:
import importlib
import utils.stage2_synthesis_plot as _sp

importlib.reload(_sp)
from utils.stage2_synthesis_plot import synthesis_cohort_panels_3cv

png3 = synthesis_cohort_panels_3cv(summary_10_pooled)